-- 코드를 입력하세요
SELECT i.REST_ID, i.REST_NAME, i.FOOD_TYPE, i.FAVORITES, i.ADDRESS, round(AVG(REVIEW_SCORE), 2) as SCORE
FROM REST_INFO i
INNER JOIN REST_REVIEW r ON r.REST_ID = i.REST_ID
WHERE ADDRESS like '서울%'
group by r.REST_ID
order by SCORE desc, FAVORITES desc